namespace Test262Runner;

internal static class SkipList
{
    internal static readonly KeyValuePair<string, string>[] Entries =
    [
        new("language/module-code/instn-local-bndng-let.js",
            "Intentional skip: module lexical TDZ typeof path currently traded off for compile-time performance"),
        new("language/expressions/arrow-function/scope-param-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/function/scope-param-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/statements/function/scope-param-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/object/scope-meth-param-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/identifier-resolution/assign-to-global-undefined.js",
            "Intentional skip: strict unresolvable assignment timing is not modeled"),
        new("language/eval-code/direct/this-value-",
            "Intentional skip: direct eval is treated as normal eval (no caller this-binding propagation)"),
        new("language/eval-code/direct/",
            "Intentional skip: direct eval is treated as normal eval (no caller this-binding propagation)"),
        new("language/eval-code/indirect/global-env-rec-eval.js",
            "Intentional skip: test depends on direct eval creating caller-local var bindings; Okojo treats direct eval as indirect/global eval"),
        new("language/eval-code/indirect/this-value-", "Intentional skip: eval always uses global-eval path in Okojo"),
        new("language/module-code/eval-this.js",
            "Intentional skip: module direct eval this-binding is not modeled; eval uses global-eval path"),
        new("language/expressions/function/unscopables-with.js",
            "Intentional skip: with statement semantics are intentionally unsupported in Okojo"),
        new("language/expressions/function/eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/call/eval-spread",
            "Intentional skip: direct eval is treated as indirect/global eval, so direct-eval-local spread-call semantics are unsupported"),
        new("language/expressions/call/eval-strictness-inherit-strict.js",
            "Intentional skip: direct eval is treated as indirect/global eval, so caller strictness is not inherited"),
        new("language/expressions/call/tco-non-eval-function-dynamic.js",
            "Intentional skip: direct eval-created local eval binding semantics are unsupported in Okojo"),
        new("language/expressions/assignment/S11.13.1_A6_T1.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-local var rebinding during assignment reference resolution is unsupported"),
        new("language/expressions/assignment/S11.13.1_A6_T2.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-local var rebinding during assignment reference resolution is unsupported"),
        new("language/types/reference/8.7.2-1-s.js",
            "Intentional skip: direct eval is treated as indirect/global eval, so caller strictness is not inherited for unresolvable assignment"),
        new("language/directive-prologue/10.1.1-8-s.js",
            "Intentional skip: direct eval is treated as indirect/global eval, so caller strictness is not inherited into eval directive-prologue early errors"),
        new("language/directive-prologue/10.1.1-5-s.js",
            "Intentional skip: direct eval is treated as indirect/global eval, so caller strictness is not inherited into eval directive-prologue early errors"),
        new("language/directive-prologue/10.1.1-14-s.js",
            "Intentional skip: direct eval is treated as indirect/global eval, so caller strictness is not inherited into eval directive-prologue early errors"),
        new("language/directive-prologue/10.1.1-30-s.js",
            "Intentional skip: direct eval is treated as indirect/global eval, so caller strictness is not inherited into eval directive-prologue early errors"),
        new("language/literals/numeric/7.8.3-3gs.js",
            "Intentional skip: direct eval is treated as indirect/global eval, so caller strictness is not inherited for legacy octal early errors"),
        new("language/literals/numeric/legacy-octal-integer.js",
            "Intentional skip: legacy octal integer literals are intentionally unsupported in Okojo"),
        new("language/arguments-object/10.5-1-s.js",
            "Intentional skip: direct eval is treated as indirect/global eval, so caller strictness is not inherited into eval assignment to arguments"),
        new("language/arguments-object/10.5-7-b-1-s.js",
            "Intentional skip: direct eval is treated as indirect/global eval, so strict eval-local arguments assignment semantics are unsupported"),
        new("language/expressions/arrow-function/scope-body-lex-distinct.js",
            "Intentional skip: direct eval is treated as normal eval (no body-lexical vs var-environment conflict checks)"),
        new("language/expressions/arrow-function/eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter/body environment conflict semantics)"),
        new("language/expressions/arrow-function/ArrowFunction_restricted-properties.js",
            "Intentional skip: deprecated caller/arguments restricted-property behavior is intentionally unsupported in Okojo"),
        new("language/expressions/object/method-definition/meth-eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/object/method-definition/gen-meth-eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/object/method-definition/async-meth-eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/generators/eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter/body environment conflict semantics)"),
        new("language/expressions/function/named-strict-error-reassign-fn-name-in-body-in-eval.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/generators/named-strict-error-reassign-fn-name-in-body-in-eval.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval function-name binding semantics)"),
        new("language/expressions/async-generator/eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/async-generator/named-eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/async-generator/named-strict-error-reassign-fn-name-in-body-in-eval.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval function-name binding semantics)"),
        new("language/expressions/async-arrow-function/eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/async-function/nameless-eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/async-function/named-eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/expressions/async-function/named-strict-error-reassign-fn-name-in-body-in-eval.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval function-name binding semantics)"),
        new("language/expressions/function/scope-body-lex-distinct.js",
            "Intentional skip: direct eval is treated as normal eval (no body-lexical vs var-environment conflict checks)"),
        new("language/expressions/generators/scope-body-lex-distinct.js",
            "Intentional skip: direct eval is treated as normal eval (no body-lexical vs var-environment conflict checks)"),
        new("language/expressions/object/scope-meth-body-lex-distinct.js",
            "Intentional skip: direct eval is treated as normal eval (no body-lexical vs var-environment conflict checks)"),
        new("language/expressions/object/scope-gen-meth-body-lex-distinct.js",
            "Intentional skip: direct eval is treated as normal eval (no body-lexical vs var-environment conflict checks)"),
        new("language/expressions/object/scope-getter-body-lex-distinc.js",
            "Intentional skip: direct eval is treated as normal eval (no body-lexical vs var-environment conflict checks)"),
        new("language/expressions/object/scope-setter-body-lex-distinc.js",
            "Intentional skip: direct eval is treated as normal eval (no body-lexical vs var-environment conflict checks)"),
        new("language/expressions/tagged-template/cache-eval-inner-function.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-local template site caching across local bindings is not modeled"),
        new("language/expressions/dynamic-import/usage-from-eval.js",
            "Intentional skip: direct eval is treated as normal eval, so import() from eval does not preserve the eval caller context"),
        new("language/expressions/compound-assignment/S11.13.2_A6.",
            "Intentional skip: direct eval is treated as normal eval, so eval-local var rebinding during compound assignment is unsupported"),
        new("language/statements/generators/scope-body-lex-distinct.js",
            "Intentional skip: direct eval is treated as normal eval (no body-lexical vs var-environment conflict checks in non-strict generators)"),
        new("language/statements/try/catch-parameter-boundnames-restriction-arguments-eval-throws.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/try/catch-parameter-boundnames-restriction-eval-eval-throws.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/variable/12.2.1-2-s.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/variable/12.2.1-3-s.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/variable/12.2.1-4-s.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/variable/12.2.1-7-s.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/variable/12.2.1-8-s.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/variable/12.2.1-18-s.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/variable/12.2.1-19-s.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/function/13.0-8-s.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/function/13.1-2-s.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/function/13.1-4-s.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/statements/function/eval-var-scope-syntax-err.js",
            "Intentional skip: test depends on direct eval inheriting outer strictness; Okojo treats direct eval as normal global eval"),
        new("language/function-code/10.4.3-1-17-s.js",
            "Intentional skip: direct eval is treated as indirect/global eval, so caller this-binding is not inherited"),
        new("language/statements/continue/S12.7_A7.js",
            "Intentional skip: direct eval is treated as normal/global eval, so eval-local continue control flow is unsupported"),
        new("language/statements/break/S12.8_A7.js",
            "Intentional skip: direct eval is treated as normal/global eval, so eval-local break control flow is unsupported"),
        new("language/statements/function/13.2-4-s.js",
            "Intentional skip: deprecated function.arguments behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-6-s.js",
            "Intentional skip: deprecated function.caller behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-9-s.js",
            "Intentional skip: deprecated function.caller behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-10-s.js",
            "Intentional skip: deprecated function.caller behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-13-s.js",
            "Intentional skip: deprecated function.arguments behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-14-s.js",
            "Intentional skip: deprecated function.arguments behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-17-s.js",
            "Intentional skip: deprecated function.arguments behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-18-s.js",
            "Intentional skip: deprecated function.arguments behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-19-b-3gs.js",
            "Intentional skip: deprecated function.caller behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-21-s.js",
            "Intentional skip: deprecated function.caller behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-22-s.js",
            "Intentional skip: deprecated function.caller behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-25-s.js",
            "Intentional skip: deprecated function.arguments behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-26-s.js",
            "Intentional skip: deprecated function.arguments behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-30-s.js",
            "Intentional skip: deprecated function caller/arguments accessors are intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-2-s.js",
            "Intentional skip: deprecated function.caller behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/13.2-5-s.js",
            "Intentional skip: deprecated function.caller behavior is intentionally unsupported in Okojo"),
        new("language/statements/function/scope-body-lex-distinct.js",
            "Intentional skip: direct eval is treated as normal eval (no body-lexical vs var-environment conflict checks)"),
        new("language/statements/class/strict-mode/arguments-callee.js",
            "Intentional skip: deprecated arguments.callee behavior is intentionally unsupported in Okojo"),
        new("language/literals/regexp/u-case-mapping.js",
            "Intentional skip: non-unicode ignoreCase canonicalization differences (e.g., U+212A) are not fully modeled"),
        new("language/expressions/object/__proto__",
            "Intentional skip: __proto__-specific legacy behavior is not supported in Okojo"),
        new("language/expressions/assignment/destructuring/obj-prop-__proto__dup.js",
            "Intentional skip: __proto__-specific legacy behavior is not supported in Okojo"),
        new("language/expressions/super/prop-expr-getsuperbase-before-topropertykey-getvalue.js",
            "Intentional skip: test depends on legacy object-literal __proto__ setup, which Okojo intentionally does not support"),
        new("language/expressions/super/prop-expr-getsuperbase-before-topropertykey-putvalue-increment.js",
            "Intentional skip: test depends on legacy object-literal __proto__ setup, which Okojo intentionally does not support"),
        new("language/expressions/super/prop-expr-getsuperbase-before-topropertykey-putvalue.js",
            "Intentional skip: test depends on legacy object-literal __proto__ setup, which Okojo intentionally does not support"),
        new("language/expressions/super/prop-expr-getsuperbase-before-topropertykey-putvalue-compound-assign.js",
            "Intentional skip: test depends on legacy object-literal __proto__ setup, which Okojo intentionally does not support"),
        new("language/expressions/super/prop-expr-cls-val-from-eval.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo, so direct-eval-specific super binding semantics are unsupported"),
        new("language/expressions/super/prop-dot-obj-val-from-eval.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo, so direct-eval-specific super binding semantics are unsupported"),
        new("language/expressions/super/prop-expr-obj-val-from-eval.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo, so direct-eval-specific super binding semantics are unsupported"),
        new("language/expressions/super/prop-dot-cls-val-from-eval.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo, so direct-eval-specific super binding semantics are unsupported"),
        new("test/built-ins/eval/private-identifiers-not-empty.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo, so direct-eval-specific private identifier early error semantics are unsupported"),
        new("built-ins/TypedArrayConstructors/ctors/no-species.js",
            "Intentional skip: test asserts legacy __proto__ behavior, which Okojo does not prioritize"),
        new("built-ins/Array/Symbol.species/",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/concat/create-species",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/concat/create-proxy.js",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/concat/create-proto-from-ctor-realm",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/concat/create-species-with-",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/concat/create-species-non-extensible",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/filter/create-species",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/filter/create-proxy.js",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/filter/create-proto-from-ctor-realm",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/filter/target-array-",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/map/create-species",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/String/prototype/matchAll/flags-undefined-throws.js",
            "Intentional skip: regex matchAll/property-observability tails are temporarily deferred while broader RegExp own-property cleanup settles"),
        new("staging/built-ins/Object/seal/seal-variable-length-typed-arrays.js",
            "Intentional skip: Object.seal on variable-length typed arrays depends on resizable/growable buffer integrity semantics not fully modeled yet"),
        new("built-ins/Array/prototype/map/create-proxy.js",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/map/create-proto-from-ctor-realm",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/map/target-array-",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/slice/create-species",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/slice/create-proxy.js",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/slice/create-proto-from-ctor-realm",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/slice/target-array-",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/splice/create-species",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/splice/create-proxy.js",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/splice/create-proto-from-ctor-realm",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/splice/target-array-",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/splice/property-traps-order-with-species.js",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/flat/target-array-",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/flatMap/target-array-",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/flatMap/this-value-ctor-object-species",
            "Intentional skip: Array[Symbol.species] is intentionally unsupported; array methods always create base Array results"),
        new("built-ins/Array/prototype/flatMap/proxy-access-count.js",
            "Intentional skip: access-count expectation depends on ArraySpeciesCreate reading constructor before FlattenIntoArray"),
        new("built-ins/Array/prototype/flat/proxy-access-count.js",
            "Intentional skip: access-count expectation depends on ArraySpeciesCreate reading constructor before FlattenIntoArray"),
        new("built-ins/Array/prototype/concat/arg-length-near-integer-limit.js",
            "Intentional skip: test attempts to concat near the maximum length limit, which is not currently modeled in Okojo. V8 do nothing for this test. Okojo do range error"),
        new("built-ins/Array/prototype/concat/create-ctor-non-object.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/concat/create-ctor-poisoned.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/concat/is-concat-spreadable-get-order.js",
            "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/filter/create-ctor-poisoned.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/filter/create-ctor-non-object.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/flatMap/this-value-ctor-non-object.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/flat/non-object-ctor-throws.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/map/create-ctor-poisoned.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/map/create-ctor-non-object.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/slice/create-ctor-poisoned.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/slice/create-ctor-non-object.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/splice/create-ctor-poisoned.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/splice/create-ctor-non-object.js", "Intentional skip: ArraySpeciesCreate."),
        new("built-ins/Array/prototype/sort/precise-comparefn-throws.js",
            "Intentional skip: this case recurses through user-defined setters until engine stack overflow; V8 also overflows, so this is not a useful Okojo conformance target right now."),
        new("built-ins/Array/prototype/sort/precise-prototype-accessors.js",
            "Intentional skip: this case recurses through user-defined setters until engine stack overflow; V8 also overflows, so this is not a useful Okojo conformance target right now."),
        new("built-ins/SharedArrayBuffer/prototype/slice/species",
            "Intentional skip: SharedArrayBuffer[Symbol.species] is intentionally unsupported in Okojo for this slice."),
        new("built-ins/TypedArrayConstructors/internals/HasProperty/infinity-with-detached-buffer.js",
            "Intentional skip: uses with-statement semantics, which Okojo intentionally does not support."),
        new("built-ins/TypedArrayConstructors/internals/HasProperty/BigInt/infinity-with-detached-buffer.js",
            "Intentional skip: uses with-statement semantics, which Okojo intentionally does not support."),
        new("language/expressions/function/unscopables-with-in-nested-fn.js",
            "Intentional skip: with statement semantics are intentionally unsupported in Okojo"),
        new("built-ins/Array/prototype/push/S15.4.4.7_A3.js",
            "Intentional skip: RangeError with value successfully pushed is not modeled in Okojo, but V8 successfully pushes the value and does not throw"),
        new("built-ins/Iterator/prototype/drop/argument-validation-failure-closes-underlying.js",
            "Intentional skip: relies on legacy object-literal __proto__ inheritance from Iterator.prototype, which Okojo intentionally does not support."),
        new("built-ins/Iterator/prototype/every/argument-validation-failure-closes-underlying.js",
            "Intentional skip: relies on legacy object-literal __proto__ inheritance from Iterator.prototype, which Okojo intentionally does not support."),
        new("built-ins/Iterator/prototype/filter/argument-validation-failure-closes-underlying.js",
            "Intentional skip: relies on legacy object-literal __proto__ inheritance from Iterator.prototype, which Okojo intentionally does not support."),
        new("built-ins/Iterator/prototype/find/argument-validation-failure-closes-underlying.js",
            "Intentional skip: relies on legacy object-literal __proto__ inheritance from Iterator.prototype, which Okojo intentionally does not support."),
        new("built-ins/Iterator/prototype/flatMap/argument-validation-failure-closes-underlying.js",
            "Intentional skip: relies on legacy object-literal __proto__ inheritance from Iterator.prototype, which Okojo intentionally does not support."),
        new("built-ins/Iterator/prototype/forEach/argument-validation-failure-closes-underlying.js",
            "Intentional skip: relies on legacy object-literal __proto__ inheritance from Iterator.prototype, which Okojo intentionally does not support."),
        new("built-ins/Iterator/prototype/map/argument-validation-failure-closes-underlying.js",
            "Intentional skip: relies on legacy object-literal __proto__ inheritance from Iterator.prototype, which Okojo intentionally does not support."),
        new("built-ins/Iterator/prototype/reduce/argument-validation-failure-closes-underlying.js",
            "Intentional skip: relies on legacy object-literal __proto__ inheritance from Iterator.prototype, which Okojo intentionally does not support."),
        new("built-ins/Iterator/prototype/some/argument-validation-failure-closes-underlying.js",
            "Intentional skip: relies on legacy object-literal __proto__ inheritance from Iterator.prototype, which Okojo intentionally does not support."),
        new("built-ins/Iterator/prototype/take/argument-validation-failure-closes-underlying.js",
            "Intentional skip: relies on legacy object-literal __proto__ inheritance from Iterator.prototype, which Okojo intentionally does not support."),
        new("built-ins/Iterator/zip/",
            "TEMP_SKIP_FUTURE_FIX_EXPERIMENTAL: Iterator.zip is still unimplemented experimental joint-iteration surface; defer until core Iterator helper set settles."),
        new("built-ins/Iterator/zipKeyed/",
            "TEMP_SKIP_FUTURE_FIX_EXPERIMENTAL: Iterator.zipKeyed is still unimplemented experimental joint-iteration surface; defer until Iterator.zip and core helper semantics settle."),
        new("built-ins/String/S15.5.5.1_A4_T1.js", "Intentional skip: with statement not supported"),
        new("language/expressions/yield/from-with.js", "Intentional skip: with statement not supported"),
        new("language/expressions/dynamic-import/syntax/valid/nested-with-",
            "Intentional skip: with statement semantics are intentionally unsupported in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/top-level-import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/top-level-import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-if-import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-if-import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-if-braceless-import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-if-braceless-import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/statements/class/decorator/",
            "Intentional skip: decorators proposal syntax is not implemented in Okojo"),
        new("language/statements/class/elements/privatename-not-valid-eval-earlyerr-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval private-environment early-error semantics)"),
        new("language/statements/class/elements/direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/private-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/nested-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/nested-private-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/arrow-body-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/arrow-body-private-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/private-derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/nested-derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/nested-private-derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/arrow-body-derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/arrow-body-private-derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval class-element private/super/new.target semantics)"),
        new("language/statements/class/elements/private-field-visible-to-direct-eval",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval private-name visibility semantics inside class elements)"),
        new("language/statements/class/elements/private-getter-visible-to-direct-eval",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval private-name visibility semantics inside class elements)"),
        new("language/statements/class/elements/private-setter-visible-to-direct-eval",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval private-name visibility semantics inside class elements)"),
        new("language/statements/class/elements/private-method-visible-to-direct-eval",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval private-name visibility semantics inside class elements)"),
        new("language/statements/class/elements/private-static-field-visible-to-direct-eval.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval private-name visibility semantics inside class elements)"),
        new("language/statements/class/elements/private-static-getter-visible-to-direct-eval.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval private-name visibility semantics inside class elements)"),
        new("language/statements/class/elements/private-static-setter-visible-to-direct-eval.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval private-name visibility semantics inside class elements)"),
        new("language/statements/class/elements/private-static-method-visible-to-direct-eval.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval private-name visibility semantics inside class elements)"),
        new("test/language/statements/class/elements/static-field-init-with-this.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval private-name visibility semantics inside class elements)"),
        new("language/expressions/dynamic-import/syntax/valid/nested-if-braceless-import-attributes-",
            "Intentional skip: dynamic import attributes syntax is not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-function-import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-function-import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-function-import-attributes-",
            "Intentional skip: dynamic import attributes syntax is not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-function-return-import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-function-return-import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-function-return-import-attributes-",
            "Intentional skip: dynamic import attributes syntax is not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-else-braceless-import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-else-braceless-import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-else-braceless-import-attributes-",
            "Intentional skip: dynamic import attributes syntax is not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-block-import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-block-import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-block-import-attributes-",
            "Intentional skip: dynamic import attributes syntax is not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-block-labeled-import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-block-labeled-import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-block-labeled-import-attributes-",
            "Intentional skip: dynamic import attributes syntax is not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-async-function-import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-async-function-import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-async-function-import-attributes-",
            "Intentional skip: dynamic import attributes syntax is not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-async-function-return-await-import-source-",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-async-function-return-await-import-defer-",
            "Intentional skip: import.defer proposal semantics are not implemented in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-async-function-return-await-import-attributes-",
            "Intentional skip: dynamic import attributes syntax is not implemented in Okojo"),
        new("language/expressions/dynamic-import/catch/nested-async-gen-await-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for nested async generators."),
        new("language/expressions/dynamic-import/catch/nested-async-gen-return-await-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for nested async generators."),
        new("language/expressions/dynamic-import/catch/nested-arrow-import-catch-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-async-arrow-function-await-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new(
            "language/expressions/dynamic-import/catch/nested-async-arrow-function-return-await-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-async-function-await-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-async-function-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-async-function-return-await-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-block-import-catch-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-block-labeled-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-do-while-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-else-import-catch-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-function-import-catch-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-if-import-catch-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/nested-while-import-catch-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/expressions/dynamic-import/catch/top-level-import-catch-eval-script-code-target.js",
            "Intentional skip: direct eval is treated as normal eval, so eval-created script code is not modeled as the caller's Script Record for dynamic import catch cases."),
        new("language/statements/async-function/eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/nested-with-script-code-valid.js",
            "Intentional skip: with statement semantics are intentionally unsupported in Okojo"),
        new("language/expressions/dynamic-import/syntax/valid/top-level-import-source-empty-str-is-valid-assign-expr.js",
            "Intentional skip: source-phase-imports/import.source proposal semantics are not implemented in Okojo"),
        new("language/expressions/class/elements/direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/nested-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/arrow-body-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/arrow-body-derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/private-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/arrow-body-private-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/private-derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/arrow-body-private-derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/nested-derived-cls-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/nested-private-direct-eval-",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("nested-private-direct-eval-err-contains-arguments.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("nested-private-derived-cls-direct-eval-contains-superproperty-1.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("nested-private-derived-cls-direct-eval-contains-superproperty-2.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/derived-cls-direct-eval-contains-superproperty-2.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/arrow-body-direct-eval-err-contains-arguments.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/arrow-body-private-direct-eval-err-contains-arguments.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/elements/static-field-init-with-this.js",
            "Intentional skip: direct eval is treated as normal eval in Okojo"),
        new("language/expressions/class/subclass-builtins/subclass-SharedArrayBuffer.js",
            "Intentional skip: SharedArrayBuffer builtin is not implemented in Okojo"),
        new("language/expressions/class/elements/private-getter-is-not-a-own-property.js",
            "Intentional skip: legacy Object.prototype.__lookupGetter__ is intentionally unsupported in Okojo"),
        new("language/expressions/class/elements/private-setter-is-not-a-own-property.js",
            "Intentional skip: legacy Object.prototype.__lookupSetter__ is intentionally unsupported in Okojo"),
        new("private-getter-is-not-a-own-property.js",
            "Intentional skip: legacy Object.prototype.__lookupGetter__ is intentionally unsupported in Okojo"),
        new("private-setter-is-not-a-own-property.js",
            "Intentional skip: legacy Object.prototype.__lookupSetter__ is intentionally unsupported in Okojo"),
        new("language/expressions/object/method-definition/async-gen-meth-eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/statements/async-generator/eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("language/statements/generators/eval-var-scope-syntax-err.js",
            "Intentional skip: direct eval is treated as normal eval (no direct-eval parameter environment semantics)"),
        new("built-ins/Function/prototype/arguments/prop-desc.js",
            "Intentional skip: Function.prototype.arguments is deprecated legacy behavior and intentionally unsupported in Okojo"),
        new("built-ins/Function/prototype/caller/prop-desc.js",
            "Intentional skip: Function.prototype.caller is deprecated legacy behavior and intentionally unsupported in Okojo"),
        new("built-ins/Function/15.3.5-",
            "Intentional skip: Function.prototype.caller/arguments legacy restricted-property behavior is intentionally unsupported in Okojo"),
        new("built-ins/Function/15.3.5.4_2-",
            "Intentional skip: Function.prototype.caller/arguments legacy restricted-property behavior is intentionally unsupported in Okojo"),
        new("built-ins/Function/prototype/caller-arguments/accessor-properties.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("built-ins/Function/prototype/bind/BoundFunction_restricted-properties.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("built-ins/Function/StrictFunction_restricted-properties.js",
            "Intentional skip: Function.prototype.caller/arguments legacy restricted-property behavior is intentionally unsupported in Okojo"),
        new("built-ins/Function/prototype/bind/S15.3.4.5_A1.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("built-ins/Function/prototype/bind/S15.3.4.5_A2.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("built-ins/Function/prototype/bind/15.3.4.5-20-2.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("built-ins/Function/prototype/bind/15.3.4.5-20-3.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("built-ins/Function/prototype/bind/15.3.4.5-21-2.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("built-ins/Function/prototype/bind/15.3.4.5-21-3.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("built-ins/GeneratorFunction/instance-restricted-properties.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("language/statements/generators/restricted-properties.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("language/statements/class/definition/methods-restricted-properties.js",
            "Intentional skip: deprecated Function.prototype.arguments/caller restricted accessor surface is intentionally unsupported in Okojo"),
        new("built-ins/Function/StrictFunction_reservedwords_with.js",
            "Intentional skip: with statement semantics are intentionally unsupported in Okojo"),
        new("language/statements/with/",
            "Intentional skip: with statement semantics are intentionally unsupported in Okojo"),
        new("built-ins/Function/prototype/toString/line-terminator-normalisation-LF.js",
            "Intentional skip: this checkout currently stores the LF fixture with CRLF line endings, so the runner cannot validate the intended source-text preservation for this exact file."),
        new("language/arguments-object/S10.6_A3_T1.js", "Intentional skip: relies on deprecated arguments.callee"),
        new("language/arguments-object/S10.6_A3_T2.js", "Intentional skip: relies on deprecated arguments.callee"),
        new("language/arguments-object/S10.6_A3_T3.js", "Intentional skip: relies on deprecated arguments.callee"),
        new("language/arguments-object/S10.6_A3_T4.js", "Intentional skip: relies on deprecated arguments.callee"),
        new("language/arguments-object/S10.6_A4.js", "Intentional skip: relies on deprecated arguments.callee"),
        new("language/arguments-object/10.6-2gs.js", "Intentional skip: relies on deprecated arguments.callee"),
        new("language/arguments-object/10.6-12-1.js", "Intentional skip: relies on deprecated arguments.callee"),
        new("language/arguments-object/10.6-14-c-4-s.js", "Intentional skip: relies on legacy arguments.callee"),
        new("language/arguments-object/10.6-12-2.js", "Intentional skip: relies on legacy arguments.callee"),
        new("language/arguments-object/10.6-13-a-1.js", "Intentional skip: relies on legacy arguments.callee"),
        new("language/arguments-object/10.6-13-a-2.js", "Intentional skip: relies on legacy arguments.callee"),
        new("language/arguments-object/10.6-13-a-3.js", "Intentional skip: relies on legacy arguments.callee"),
        new("language/arguments-object/10.6-13-c-1-s.js", "Intentional skip: relies on legacy arguments.callee"),
        new("language/arguments-object/10.6-13-c-2-s.js", "Intentional skip: relies on legacy arguments.callee"),
        new("language/arguments-object/10.6-13-c-3-s.js", "Intentional skip: relies on legacy arguments.callee"),
        new("language/arguments-object/10.6-14-c-1-s.js", "Intentional skip: relies on legacy arguments.callee")
    ];
}
