import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const stringsRoot = path.join(
  root,
  'third_party',
  'test262',
  'test',
  'built-ins',
  'RegExp',
  'property-escapes',
  'generated',
  'strings'
);
const outputPath = path.join(
  root,
  'src',
  'EcmaRegex',
  'Internal',
  'UnicodeStringPropertyData.Generated.cs'
);

function normalize(value) {
  return value.toUpperCase().replaceAll('_', '');
}

function collectFiles(directory) {
  const result = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) result.push(...collectFiles(fullPath));
    else if (entry.isFile() && entry.name.endsWith('.js')) result.push(fullPath);
  }
  return result;
}

const aliases = new Map();
const sets = [];
const files = collectFiles(stringsRoot)
  .filter(filePath => !path.basename(filePath).includes('-negative'))
  .filter(filePath => !path.basename(filePath).includes('-u.js'))
  .sort();
for (const filePath of files) {
  let strings = null;
  let propertyName = null;
  const context = {
    testPropertyOfStrings({ regExp, expression, matchStrings }) {
      const match = regExp.source.match(/\\p\{([^}]+)\}/);
      if (match) propertyName = normalize(match[1]);
      strings = matchStrings;
    },
    assert() {},
  };
  vm.createContext(context);
  try {
    vm.runInContext(fs.readFileSync(filePath, 'utf8'), context, { filename: filePath });
  } catch (error) {
    throw new Error(`${filePath}: ${error?.message ?? error}`);
  }
  if (strings === null || propertyName === null) continue;
  const setId = sets.length;
  sets.push(strings);
  const previous = aliases.get(propertyName);
  if (previous !== undefined && previous !== setId)
    throw new Error(`Alias collision for ${propertyName}: ${previous} versus ${setId}`);
  aliases.set(propertyName, setId);
}

function escapeString(value) {
  const builder = [];
  for (let i = 0; i < value.length; i++) {
    const unit = value.charCodeAt(i);
    if (unit >= 0x20 && unit < 0x7f && String.fromCharCode(unit) !== '"' && String.fromCharCode(unit) !== '\\') {
      builder.push(String.fromCharCode(unit));
    } else {
      builder.push(`\\u${unit.toString(16).toUpperCase().padStart(4, '0')}`);
    }
  }
  return builder.join('');
}

const lines = [
  '// <auto-generated />',
  '// Generated from the pinned Test262 Unicode 17.0.0 RegExp string-property tests.',
  'namespace EcmaRegex.Internal;',
  '',
  'internal static partial class UnicodePropertyDatabase',
  '{',
  '    private static readonly string[][] s_stringSets =',
  '    [',
];
for (const strings of sets) {
  lines.push('        [');
  for (const value of strings)
    lines.push(`            "${escapeString(value)}",`);
  lines.push('        ],');
}
lines.push(
  '    ];',
  '',
  '    private static readonly Dictionary<string, int> s_stringAliases = new(StringComparer.Ordinal)',
  '    {',
);
for (const [alias, setId] of [...aliases.entries()].sort((left, right) => left[0].localeCompare(right[0])))
  lines.push(`        ["${alias}"] = ${setId},`);
lines.push(
  '    };',
  '',
    '    internal static bool TryResolveStringsNormalized(string normalized, out string[] strings)',
  '    {',
  '        if (s_stringAliases.TryGetValue(normalized, out int setId))',
  '        {',
  '            strings = s_stringSets[setId];',
  '            return true;',
  '        }',
  '        strings = [];',
  '        return false;',
  '    }',
  '}',
  '',
);
fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
console.log(`Wrote ${outputPath}: ${sets.length} string properties, ${aliases.size} aliases`);
for (const [alias, setId] of aliases)
  console.log(`  ${alias}: ${sets[setId].length} strings`);
