import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generatedRoot = path.join(
  root,
  'third_party',
  'test262',
  'test',
  'built-ins',
  'RegExp',
  'property-escapes',
  'generated'
);
const outputPath = path.join(root, 'src', 'EcmaRegex', 'Internal', 'UnicodePropertyData.Additional.Generated.cs');

function collectFiles(directory) {
  const result = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) result.push(...collectFiles(fullPath));
    else if (entry.isFile() && entry.name.endsWith('.js')) result.push(fullPath);
  }
  return result;
}

function normalize(value) {
  return value.toUpperCase().replaceAll('_', '');
}

function rangesFor(specification) {
  const ranges = specification.ranges.map(([start, end]) => [start, end]);
  for (const codePoint of specification.loneCodePoints)
    ranges.push([codePoint, codePoint]);
  ranges.sort((left, right) => left[0] - right[0]);
  const merged = [];
  for (const [start, end] of ranges) {
    const previous = merged.at(-1);
    if (previous && start <= previous[1] + 1) previous[1] = Math.max(previous[1], end);
    else merged.push([start, end]);
  }
  return merged;
}

function buildString(specification) {
  return specification;
}

const sets = [];
const aliases = new Map();
const files = collectFiles(generatedRoot)
  .filter(filePath => !filePath.includes(`${path.sep}strings${path.sep}`))
  .filter(filePath => !path.basename(filePath).includes('-negated'))
  .sort();
for (const filePath of files) {
  let ranges = null;
  const expressions = [];
  const context = {
    buildString,
    testPropertyEscapes(regex, matchSymbols) {
      if (ranges === null && regex.source.includes('\\p{')) ranges = rangesFor(matchSymbols);
      const match = regex.source.match(/\\p\{([^}]+)\}/);
      if (match) expressions.push(normalize(match[1]));
    },
    assert() {},
  };
  vm.createContext(context);
  try {
    vm.runInContext(fs.readFileSync(filePath, 'utf8'), context, { filename: filePath });
  } catch (error) {
    throw new Error(`${filePath}: ${error?.message ?? error}`);
  }
  if (ranges === null || expressions.length === 0) continue;
  const setId = sets.length;
  sets.push(ranges);
  for (const alias of expressions) {
    const previous = aliases.get(alias);
    if (previous !== undefined && previous !== setId)
      throw new Error(`Alias collision for ${alias}: ${previous} versus ${setId}`);
    aliases.set(alias, setId);
  }
}

const lines = [
  '// <auto-generated />',
  '// Generated from the pinned Test262 Unicode 17.0.0 RegExp property tests.',
  'namespace EcmaRegex.Internal;',
  '',
  'internal static class UnicodePropertyDatabaseAdditional',
  '{',
  '    private static readonly CharSet[] s_sets =',
  '    [',
];
for (const ranges of sets) {
  lines.push('        new([', ...ranges.map(([start, end]) =>
    `            new CodePointRange(0x${start.toString(16).toUpperCase()}, 0x${end.toString(16).toUpperCase()}),`), '        ]),');
}
lines.push(
  '    ];',
  '',
  '    private static readonly Dictionary<string, int> s_aliases = new(StringComparer.Ordinal)',
  '    {',
);
for (const [alias, setId] of [...aliases.entries()].sort((left, right) => left[0].localeCompare(right[0])))
  lines.push(`        ["${alias}"] = ${setId},`);
lines.push(
  '    };',
  '',
  '    internal static bool TryResolve(string normalized, out int propertyId) =>',
  '        s_aliases.TryGetValue(normalized, out propertyId);',
  '',
  '    internal static CharSet GetSet(int propertyId) => s_sets[propertyId];',
  '}',
  '',
);
fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
console.log(`Wrote ${outputPath}: ${sets.length} sets, ${aliases.size} aliases`);
